global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'proxmox-node'
    static_configs:
      - targets: ['10.0.10.201:9100']


  # - job_name: 'proxmox-api'
  #   static_configs:
  #     - targets: ['10.0.10.201:9221']