global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Change it to your Proxmox ip 

  - job_name: 'proxmox-api'
    static_configs:
      - targets: [ 'localhost :9221' ] # Change it to your Proxmox ip 
